#!/usr/bin/env node
const { startServer } = require('../app')
const throng = require('throng')
console.log('hahaha')
throng({
  workers: process.env.WEB_CONCURRENCY || 1,
  lifetime: Infinity
}, startServer)
